### PR TITLE
Events test

### PR DESCRIPTION
**Pull request by cjsewell07**
Adding the tests correction and functional testing for the dates. Recommended pulling, for testing purposes.

### CODE REVIEW

**Review by AlexTorresD — APPROVED** [review]
Mostly testing. Had to delete a file due to it being depreciated. Minor fix in simple cov, trivial change. Looks good.

**Review by AlexTorresD — APPROVED** [review]

**Comment by writchie3** [comment]
Looks good overall, Alex needs to change a line to make sure testing will work when combined but overall acceptable

**Review by AndrewArzola — CHANGES_REQUESTED** [review]
Pull then create a new pull request

**Review by AlexTorresD — CHANGES_REQUESTED** [review]
You're going to need to pull from test and make sure not to run rspec. Cov file has too many changes needed.

**Review by AndrewArzola — APPROVED** [review]

**Review by AlexTorresD — APPROVED** [review]
Testing looks good may need to test more later

**Pull request merged**
